groups:
  - name: demo_alerts
    rules:
      - alert: DemoAppHighErrorRate
        expr: |
          sum(rate(app_requests_total{code="500"}[2m]))
          /
          sum(rate(app_requests_total[2m]))
          > 0.05
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Demo app error rate > 5%"
          description: "The demo app is returning >5% 500s for 1 minute."

      - alert: NodeExporterDown
        expr: up{job="node"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "node_exporter down"
          description: "Prometheus cannot scrape node_exporter."